sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect
  - npm install -g particle-cli
  - curl https://github.com/dakl/ci-scripts/bootstrap.sh | bash

before_script:
  - ./ci-scripts/ci-particle.py login

script:
  - ./ci-scripts/ci-particle.py build

deploy:
  provider: script
  skip_cleanup: true
  script: ./ci-scripts/ci-particle.py flash
  on:
    branch: master